# Generated by Django 3.2.3 on 2021-06-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilities',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
