# Generated by Django 3.2.3 on 2021-06-23 21:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facilities_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
