# Generated by Django 3.2.3 on 2021-06-23 14:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('advert_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('advert_img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=50)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=20, null=True)),
                ('home_advert', models.BooleanField(default=False)),
                ('house_advert', models.BooleanField(default=False)),
                ('footer_advert', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
