# Generated by Django 3.2.3 on 2021-06-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='advert_img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
