# Generated by Django 3.2.3 on 2021-06-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='news_img',
            field=models.ImageField(default='testimon1.jpg.jpg', upload_to='images'),
        ),
    ]
